### ISSUE TITLE
how do i resolve this   import colors from "HSColors";  

### ISSUE THREAD

**Issue by jpca999** [react-native-training/react-native-elements-app#1]
i couldnt find any npm package for this.

**Comment by sparky1** [comment]
@jpca999 
me neither 

@Monte9  Could u pls show us where can we find the "HSColors" pageckage?

thx

**Comment by sparky1** [comment]
found it.
src/config/colors.js

**Comment by Monte9** [comment]
@sparky1 yes, you are right. It's a file that exists in our source code. 

@jpca999 here is the file: https://github.com/react-native-training/react-native-elements/blob/master/src/config/colors.js

We can import the file without using absolute paths becuase of this:
```
/**
 * @providesModule HSColors
 */
```

Hope this helps.

**Comment by sparky1** [comment]
thanks a lot  .@Monte9
