### ISSUE TITLE
Error while loading:Experience

### ISSUE THREAD

**Issue by pigflymoon** [react-native-training/react-native-elements-app#3]
Hi,there

When I used Expo client on my iphone, it comes out an error as follows:
![1818290352](https://user-images.githubusercontent.com/22825982/33155629-f866edca-d056-11e7-8a38-e64771c69871.jpg)
then try to run yarn on mac:
it has an error:
`yarn
yarn install v0.23.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error https://github.com/expo/react-native/archive/sdk-16.0.0.tar.gz: Bad hash. Expected "b80f46d93adc813ac7ad4ced6e0f44eb468bdc9b" but got "340ffb8d9e2516c727fcd7419b3e0b13f424ed6f"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

Is this a versioning issue, or something to be fixed? Are there any workarounds for now?

Thank you !

**Comment by xavier-villelegier** [comment]
@pigflymoon This has been fixed, thanks!
